### ISSUE TITLE
Sean to fix domains so rxloop.com.au is the final 'destination" (not gploop.com anymore)

### ISSUE THREAD

**Issue by SHeffernan** [SHeffernan/RxLoop#30]

**Comment by SHeffernan** [comment]
Paul may need to provide help with editing Amazon instance which refers to gploop.

**Comment by pwhipp** [comment]
I just need to enable the domain in the nginx dispatch and in the 'allowed hostnames'. Once you've got the domain pointing in the right place, assign this to me and I'll only need a few minutes to sort it out - be sure to include all the domain names you want to use for which site in a comment here.

**Comment by SHeffernan** [comment]
I think that I’ve diverted 
•	rapidreseach.com.au
•	rxloop.com
•	rxloop.com.au
site to the elastic IP …??

We don't need the gploop addresses to be active - if that saves space/resources.
If it doesn't make a difference, then turn off gploop later.

Is that enough information?
